### ISSUE TITLE
https://cloud.ibm.com/docs/customer-portal?topic=customer-portal-customerportal_accuserprof#cp_edituservpnaccess

### ISSUE THREAD

**Issue by TimmyAtIBM** [IBM-Bluemix-Docs/customer-portal#7]
https://cloud.ibm.com/docs/customer-portal?topic=customer-portal-customerportal_accuserprof#cp_edituservpnaccess

it's wrong.... there is not Account > Users any more.  Needs to update the instructions to point to Access(IAM) > Users

**Comment by mekaufman** [comment]
@hlucey I talked with Tim. These instructions are for SL portal for those users still using it, so it is not incorrect bc it shouldn't be doc'ing IAM UI at this time.
