### ISSUE TITLE
On the Making a Payment page, there are a number of references to Softlayer which should likely be IBM Cloud now.  

### ISSUE THREAD

**Issue by chris-ratcliffe** [IBM-Bluemix-Docs/customer-portal#8]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
Looks like a few older Softlayer references were not updated to IBM Cloud.

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/customer-portal?topic=customer-portal-cp_makepayment#customerportal_makepayment

3. Do you have a suggestion about how to resolve the issue?
Likely just a search and replace.

**Comment by mekaufman** [comment]
@chris-ratcliffe Thank you for taking the time to report this. This section of the docs is intended to still reference the control portal and SoftLayer as we still have customers using that require using the legacy environment as-is and not the unified experience on IBM Cloud. At this time, we have been directed to keep this content as it stands today. We have separate documentation for using the unified experience on cloud.ibm.com in the managing your account and billing sections (for example: https://cloud.ibm.com/docs/billing-usage?topic=billing-usage-linkedusage#linkedusage).
